//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accounts
    {
        public Accounts()
        {
            this.LibraryBooks = new HashSet<LibraryBooks>();
            this.ReaderReviews = new HashSet<ReaderReviews>();
            this.ServiceRequests = new HashSet<ServiceRequests>();
            this.UserBookCollections = new HashSet<UserBookCollections>();
            this.UserComplaints = new HashSet<UserComplaints>();
        }
    
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string DisplayName { get; set; }
        public int RoleId { get; set; }
        public bool IsFrozen { get; set; }
    
        public virtual UserRoles UserRoles { get; set; }
        public virtual ICollection<LibraryBooks> LibraryBooks { get; set; }
        public virtual ICollection<ReaderReviews> ReaderReviews { get; set; }
        public virtual ICollection<ServiceRequests> ServiceRequests { get; set; }
        public virtual ICollection<UserBookCollections> UserBookCollections { get; set; }
        public virtual ICollection<UserComplaints> UserComplaints { get; set; }
    }
}
