//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintCategories
    {
        public ComplaintCategories()
        {
            this.UserComplaints = new HashSet<UserComplaints>();
        }
    
        public int Id { get; set; }
        public string Dname { get; set; }
    
        public virtual ICollection<UserComplaints> UserComplaints { get; set; }
    }
}
