//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class GenreCatalog
    {
        public GenreCatalog()
        {
            this.LibraryBooks = new HashSet<LibraryBooks>();
        }
    
        public int Id { get; set; }
        public string Dname { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<LibraryBooks> LibraryBooks { get; set; }
    }
}
