//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibraryBooks
    {
        public LibraryBooks()
        {
            this.ReaderReviews = new HashSet<ReaderReviews>();
            this.ServiceRequests = new HashSet<ServiceRequests>();
            this.UserBookCollections = new HashSet<UserBookCollections>();
            this.UserComplaints = new HashSet<UserComplaints>();
            this.GenreCatalog = new HashSet<GenreCatalog>();
        }
    
        public int Id { get; set; }
        public string Dname { get; set; }
        public string Description { get; set; }
        public string CoveringUri { get; set; }
        public string Content { get; set; }
        public int AuthorId { get; set; }
        public bool IsFrozen { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual ICollection<ReaderReviews> ReaderReviews { get; set; }
        public virtual ICollection<ServiceRequests> ServiceRequests { get; set; }
        public virtual ICollection<UserBookCollections> UserBookCollections { get; set; }
        public virtual ICollection<UserComplaints> UserComplaints { get; set; }
        public virtual ICollection<GenreCatalog> GenreCatalog { get; set; }
    }
}
