//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YP11DANEntities : DbContext
    {
        public YP11DANEntities()
            : base("name=YP11DANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accounts> Accounts { get; set; }
        public DbSet<CollectionTypes> CollectionTypes { get; set; }
        public DbSet<ComplaintCategories> ComplaintCategories { get; set; }
        public DbSet<GenreCatalog> GenreCatalog { get; set; }
        public DbSet<LibraryBooks> LibraryBooks { get; set; }
        public DbSet<ReaderReviews> ReaderReviews { get; set; }
        public DbSet<ServiceRequests> ServiceRequests { get; set; }
        public DbSet<ServiceRequestTypes> ServiceRequestTypes { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<UserBookCollections> UserBookCollections { get; set; }
        public DbSet<UserComplaints> UserComplaints { get; set; }
        public DbSet<UserRoles> UserRoles { get; set; }
    }
}
