//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReaderReviews
    {
        public ReaderReviews()
        {
            this.UserComplaints = new HashSet<UserComplaints>();
        }
    
        public int Id { get; set; }
        public int BookId { get; set; }
        public int UserId { get; set; }
        public string Content { get; set; }
        public int Rating { get; set; }
        public System.DateTime Datetime { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual LibraryBooks LibraryBooks { get; set; }
        public virtual ICollection<UserComplaints> UserComplaints { get; set; }
    }
}
