//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequests
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int RequestTypeId { get; set; }
        public Nullable<int> TargetBookId { get; set; }
        public string Content { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual LibraryBooks LibraryBooks { get; set; }
        public virtual ServiceRequestTypes ServiceRequestTypes { get; set; }
    }
}
