//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YP01
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBookCollections
    {
        public int UserId { get; set; }
        public int BookId { get; set; }
        public int CollectionTypeId { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual CollectionTypes CollectionTypes { get; set; }
        public virtual LibraryBooks LibraryBooks { get; set; }
    }
}
